### ISSUE TITLE
How to configure plugin via Docker Compose labels?

### ISSUE THREAD

**Issue by justinmayer** [solution-libre/traefik-plugin-robots-txt#10]
First of all, thank you for creating this very useful Traefik plugin! 🌟

I have tried various approaches to configure this plugin using Docker Compose labels, including:…

```yaml
      - "--experimental.plugins.enabled=true"
      - "--experimental.plugins.robots-txt.modulename=github.com/solution-libre/traefik-plugin-robots-txt"
      - "--experimental.plugins.robots-txt.version=v0.2.0"
      […]
      - "traefik.http.routers.my-site.middlewares=robots-txt"
      - "traefik.http.middlewares.robots-txt.plugin.traefik-plugin-robots-txt.aiRobotsTxt=true"
```

… but I keep getting errors such as:

```
traefik  | time="2025-05-19T07:33:54Z" level=error msg="invalid middleware \"robots-txt@docker\" configuration:
invalid middleware type or middleware does not exist" entryPointName=https routerName=my-site@docker
```

Any idea what I might be missing?

**Comment by FlorentPoinsaut** [comment]
Hi,

Thank you!

Because you write `experimental.plugins.robots-txt` you need use `robots-txt` in the label too.

```
      - "traefik.http.routers.my-site.middlewares=robots-txt"
      - "traefik.http.middlewares.robots-txt.plugin.robots-txt.aiRobotsTxt=true"
```

I will fix the README file that contains an error in the example.

Regards,

**Comment by justinmayer** [comment]
I’m sorry — I should have been more clear. I had already tried that exact configuration, but unfortunately I still get the same error.

**Comment by justinmayer** [comment]
At this stage, I am only testing the plugin in a single router. I have the static configuration in a `compose-traefik.yml` file, with the dynamic configuration in a separate `compose-caddy.yml` file. I then run `docker compose -f compose-traefik.yml -f compose-caddy.yml […]` to include all the directives.

As seen below, the only relevant dynamic configuration that I have added is the two lines we have discussed above:

```yaml
# compose-traefik.yml
---
version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"

      # Plugins
      - "--experimental.plugins.enabled=true"
      - "--experimental.plugins.robots-txt.modulename=github.com/solution-libre/traefik-plugin-robots-txt"
      - "--experimental.plugins.robots-txt.version=v0.2.0"
      […]


# compose-caddy.yml
---
version: "3.9"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-site.rule=Host(`example.com`) || Host(`www.example.com`)"
      - "traefik.http.routers.my-site.entrypoints=https"
      - "traefik.http.routers.my-site.tls=true"
      - "traefik.http.routers.my-site.tls.certresolver=httpresolver"
      - "traefik.http.routers.my-site.service=caddy1"
      - "traefik.http.routers.my-site.middlewares=www-middleware"
      - "traefik.http.routers.my-site.middlewares=robots-txt"
      […]
      - "traefik.http.middlewares.robots-txt.plugin.robots-txt.aiRobotsTxt=true"
      […]
```
